# Generated by Django 5.2 on 2025-04-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_threegenimage_dr_children_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threegenimage',
            name='instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
